kind: Pod
apiVersion: v1
metadata:
  name: nexus-app
  labels:
    app: nexus
spec:
  containers:
    - name: nexus-app
      image: sonatype/nexus3:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data-volume
  volumes:
    - name: nexus-data-volume
      persistentVolumeClaim:
        claimName: nexus-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
    - port: 8081
