apiVersion: v1
kind: Namespace
metadata:
  name: nexus-ns

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: nexus
  name: nexus
  namespace: nexus-ns

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nexus
  labels:
    k8s-app: nexus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: nexus
  namespace: nexus-ns

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: nexus
  name: nexus
  namespace: nexus-ns
spec:
  replicas: 1
  template:
    metadata:
      name: nexus
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: nexusport
      serviceAccountName: nexus

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-ns
spec:
  ports:
  - nodePort: 32000
    port: 443
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: nexus
  sessionAffinity: None
  type: NodePort
