kind: Pod
apiVersion: v1
metadata:
  name: nexus-app
  labels:
    app: nexus
spec:
  containers:
    - name: nexus-app
      image: sonatype/nexus3:latest
      imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
    - port: 8081
