dist: trusty
language: clojure

cache:
  directories:
  - $HOME/.m2

services:
  - docker

stages:
  - build
  - integrationtest

jobs:
  include:
    - stage: build
      script:
        - # build
        - lein eastwood
        - lein test
        - lein uberjar
        - md5sum target/uberjar/dda-k8s-standalone.jar > target/uberjar/dda-k8s-standalone.jar.md5
        - # create docker image
        - docker build -t dda-k8s-crate --file integration/docker/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-k8s-crate-test --file integration/docker/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key:
            secure: "PytWrT6c/R49peVfQkiHHgDH3zUVENDcIHQ7L42TRlvETKHcc5zA2krtN6EbGAnhNe0KMl+YdZQpPJyAQJH1sd9n+c1XVytwnbdQ/j9CACB8j8X/i9D6OBBMLaVod4N9OO6rs415UFnfQw87XTorcKJamAunEIQgYFgxWvbJS/PCiP2E7H/o28fdIt3uTFKaVhab6FS1PG87Pnfxniowgn8S4BisyE86REnR4kodQraD4ApkD3AXmKfsvJ7QY48PSboF+AdoIXo4p8m4TFQhQUOwMYG0+m31qv/S8PAWPAPFalqDJPR204X1jImo9xe2IpnprMgNUEit/jH+Q22ts3ZsCFPSU0knlFe6ecaplV9+0958uhcR4XXBFWDWj1/ynMisXtsufGtkvPDup3a5wKItuv21T/lMiK9zZZNtwsCmcqhvbM3oNvrEO6DueeBukKICijcJIMEIOk1mlcdsscC45AcK2kcvdtCAuVx9HToKomoaQUfcNOAP8S2o69RQmytMKplVD+vCKHdepc2P9jg9ksQ3S5bgwaZMqg8zWUGOMnW49Nw0BotAOp3Y1AKAi/gAj4/1fNbkWR8YFnfHDgexbt0T2tJG+YLOzaDY0/YcPJvNoVSHaJ8vpFYVmoXPka9M5ztdFoRnMeUFPMTmLj38Cd1Ht76J1ueK11Qzk3Y="
          file:
            - target/uberjar/dda-k8s-standalone.jar
            - target/uberjar/dda-k8s-standalone.jar.md5
