dist: trusty
language: clojure

services:
  - docker

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - lein test
        - lein uberjar
        - md5sum target/uberjar/dda-k8s-standalone.jar > target/uberjar/dda-k8s-standalone.jar.md5
        - sha256sum target/uberjar/dda-k8s-standalone.jar > target/uberjar/dda-k8s-standalone.jar.sha256
        - sha512sum target/uberjar/dda-k8s-standalone.jar > target/uberjar/dda-k8s-standalone.jar.sha512
        - # create docker image
        - # docker build -t dda-k8s-crate --file integration/docker/image/Dockerfile .
        - # docker build -t dda-k8s-crate --file integration/docker/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          overwrite: true
          api_key:
            secure: "nC6weyl4n+Y/BOsyNFOsrTsCnKw1xFcPivlL5RV5LqXl6lIw3CO+FcgJbxsCXnEJio+/vGCDqxKAANHlifAPbr2oHhstwBL97dZQ45MMyvrGhdUOtlAxcLxJcSwFSdnqrJ+dwoXShT/x2BC6ZGBcXFNEl+LnqtEfAKlFKwrHhTibNAWVdMEFSNevgqrP2XK0v2wP39q/vX0su0Wwj71WoTKNVZKKNuPZcaUa9cse+wf4KlkIimkXtXmbB8fnk4lSTmQW4ps7RBR6q9jRtPCFO5+B1bmJ9AvB0YbWAtWsFJBgpEejCNUGvVA3Q2sm6Y3XWEIgP9hPyKxglL36RKcL7xMRc4vDey8xKXsmG3XN+lgiw5rlwSwlOnXcveeb6+fQB4G7OqExCzfVvRNFLab182Wh2u3TEGpujPYX6Ee0xteYgxaKceNVCiCMjOkX1RqB+tOSaQpw2e7IhdMV8hOXc/1INeKUlwLuSNS5kGuK5hLpLDGFxP655oyfS47FNA8E2RJtiA/P+w3FGphfA6P+EafV+VqpwNIhuzrBwPVxnsfm3MrdBJFWPCfauPzmocPkp0cVCFVj2fY+ZT8aLmVrAo/lDC3wQWpWN4FwF7Nc9o7VGOLGHt4qCpzmwkiEPjYg3UNdecHe6KiAEIfgddftBDraADlBIkG/9VJPtTO/yQw="
          file:
            - target/uberjar/dda-k8s-standalone.jar
            - target/uberjar/dda-k8s-standalone.jar.md5
            - target/uberjar/dda-k8s-standalone.jar.sha256
            - target/uberjar/dda-k8s-standalone.jar.sha512
